# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ultmate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

import QueryUtil


from PyQt5.QtWidgets import QApplication, QMainWindow, QMessageBox

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 712)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(30, 110, 891, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(950, 110, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 180, 1101, 511))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(290, 20, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton.setFont(font)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(490, 20, 131, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_2.setFont(font)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(670, 20, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.radioButton_3.setFont(font)
        self.radioButton_3.setObjectName("radioButton_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "文献查找"))
        self.pushButton.setText(_translate("MainWindow", "查找"))
        self.radioButton.setText(_translate("MainWindow", "模糊查询"))
        self.radioButton_2.setText(_translate("MainWindow", "精确查询"))
        self.radioButton_3.setText(_translate("MainWindow", "多字段查询"))

        # self.pushButton.clicked.connect(self.errorMsg)
        self.radioButton.setChecked(True)
        self.pushButton.clicked.connect(self.search)

        # print(self.radioButton.isChecked())

        self.radioButton.clicked.connect(self.checkR1)
        self.radioButton_2.clicked.connect(self.checkR2)


    def checkR1(self):
        # print(self.radioButton.isChecked())
        self.textEdit.setText("请输入 字段名:查询内容 进行模糊查询，例如：引文:《青海大通长宁遗址》")

    def checkR2(self):
        self.textEdit.setText('请输入 字段名:查询内容 进行精确查询，例如：作者:李雪霞,彭文')

    def errorMsg(self):
        msg_box = QMessageBox(QMessageBox.Warning, '提示', '请先选择查询模式！')
        msg_box.exec_()

    def search(self):
        # print("hello")
        result = []
        if self.radioButton.isChecked():
            like = self.textEdit.toPlainText()
            result = QueryUtil.search(like, 1)
        elif self.radioButton_2.isChecked():
            pre = self.textEdit.toPlainText()
            result = QueryUtil.search(pre, 2)
            print(result)
        # self.textBrowser.setText(result[0].get('_source').get("篇名"))


        for r in result:
            # self.textEdit.setInputMethodHints(hints='halo')

            source = r.get('_source')
            map = {}
            map.items()
            strRe = ''
            for k, v in source.items():
                strRe = strRe + k + ' : ' + v
            strRe = strRe + '\n' + '=========================================================================================\n=========================================================================================\n'
            self.textBrowser.append(strRe)




if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    # ui.ini()
    MainWindow.show()
    sys.exit(app.exec_())
